### ISSUE TITLE
Impossible to regenerate handlers for Object with @Tunables

### ISSUE THREAD

**Issue by agdphd** [cytoscape/cytoscape-api#2]
The current design of AbstractTunableInterceptor makes it impossible to re-generate the handlers for an Object with @Tunables. The logic of the loadTunables method ([source](https://github.com/cytoscape/cytoscape-api/blob/develop/work-api/src/main/java/org/cytoscape/work/AbstractTunableInterceptor.java#L93)) caches the generated Handlers and reuses the old ones if the Object is matched; in cases where the @Tunable fields of the Object have changed, the Handlers will not be updated.

This could be fixed by simply removing the caching logic (all references to handlerMap), but I don't know the codebase well enough to know whether this will break something else. I'm happy to throw together a PR with a patch.

**Comment by mikekucera** [comment]
commit 47b6079
