### ISSUE TITLE
Please add a license to this repo

### ISSUE THREAD

**Issue by mbrukman** [cytoscape/cytoscape-api#9]
Could you please add an explicit LICENSE file to the repo so that it's clear under what terms the content is provided, and under what terms user contributions are licensed?

Per [GitHub docs on licensing](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license):

> Generally speaking, the absence of a license means that the default copyright laws apply. This means that you retain all rights to your source code and that nobody else may reproduce, distribute, or create derivative works from your work. This might not be what you intend.

Thanks!

**Comment by bdemchak** [comment]
That's not what default copyright laws mean. Additionally, please note that each of the files in this repo are individually tagged with a license, and that the license we use is LGPL2.1. The license is also stated on the download page for our organization: cytoscape.org . I think we're fine.
